name: gnn-sparsification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - pytorch-geometric
  - networkx=3.1
  - scipy=1.11.0
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pandas=2.0.3
  - jupyter=1.0.0
  - jupyterlab=4.0.2
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - black=23.3.0
  - pylint=2.17.4
  - pyyaml=6.0
  - tqdm=4.65.0
  - pip:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
